from PIL import Image, ImageOps, ImageChops
import matplotlib.pyplot as plt



obraz1 = Image.open('obraz_mw.jpg')
obraz1 = obraz1.convert('RGBA')
r,g,b,a = obraz1.split()
obraz2 = obraz1.convert('RGB')
obraz3 = Image.new('RGB', obraz1.size,(255,255,255))
obraz3.paste(obraz2, (0,0), a)
obraz3.save('obraz3.png')
obraz3.show()

porownanie = ImageChops.difference(obraz2, obraz3)
# porownanie.show()

obraz_tmp1 = obraz3.convert('CMYK')
obraz_tmp2 = obraz3.convert('YCbCr')
obraz_tmp3 = obraz3.convert('HSV')

plt.figure(figsize=(32,32))
plt.subplot(3,3,1)
plt.title('obraz CMYK')
plt.imshow(obraz_tmp1)
plt.axis('off')
plt.subplot(3,3,2)
plt.title('obraz yCbCr')
plt.imshow(obraz_tmp2)
plt.axis('off')
plt.subplot(3,3,3)
plt.title('obraz HSV')
plt.imshow(obraz_tmp3)
plt.axis('off')
plt.subplots_adjust(0.5, 0.5)
plt.savefig('fig1.png')
# plt.show()



c,m,y,k = obraz_tmp1.split()
y,cb,cr = obraz_tmp2.split()
h,s,v = obraz_tmp3.split()



plt.figure(figsize=(32,32))
plt.subplot(4,4,1)
plt.title('kanal C ')
plt.imshow(c, 'gray')
plt.axis('off')
plt.subplot(4,4,2)
plt.title('kanal M')
plt.imshow(m, 'gray')
plt.axis('off')
plt.subplot(4,4,3)
plt.title('kanal Y')
plt.imshow(y, 'gray')
plt.axis('off')
plt.subplot(4,4,4)
plt.title('kanal K')
plt.imshow(k, 'gray')
plt.axis('off')
plt.subplots_adjust(0.5, 0.5)
plt.savefig('cmyk.png')
# plt.show()



plt.figure(figsize=(32,32))
plt.subplot(3,3,1)
plt.title('kanal Y')
plt.imshow(y, 'gray')
plt.axis('off')
plt.subplot(3,3,2)
plt.title('kanal Cb')
plt.imshow(cb, 'gray')
plt.axis('off')
plt.subplot(3,3,3)
plt.title('kanal Cr')
plt.imshow(cr, 'gray')
plt.axis('off')
plt.subplots_adjust(0.5, 0.5)
plt.savefig('ycbcr.png')
# plt.show()

plt.figure(figsize=(32,32))
plt.subplot(3,3,1)
plt.title('kanal H')
plt.imshow(h, 'gray')
plt.axis('off')
plt.subplot(3,3,2)
plt.title('kanal S')
plt.imshow(s, 'gray')
plt.axis('off')
plt.subplot(3,3,3)
plt.title('kanal V')
plt.imshow(v, 'gray')
plt.axis('off')
plt.subplots_adjust(0.5, 0.5)
plt.savefig('hsv.png')
# plt.show()

obraz4=Image.open("obraz2_mw.jpg")
tlo=obraz4.resize(obraz1.size,1)
print(obraz1.size, tlo.size)
r,g,b,a=obraz1.split()
tlo1=tlo.copy()
tlo1.paste(obraz1,(0,0),a)
tlo1.show()
ob_1copy=obraz1.copy()
ob_1copy.paste(tlo,(0,0),a)
ob_1copy.show()

plt.figure(figsize=(8,8))
plt.subplot(1,2,1)
plt.title('obraz1 wklejony w obraz4')
plt.imshow(tlo1, 'gray')
plt.axis('off')
plt.subplot(1,2,2)
plt.title('obraz4 wklejony w obraz1')
plt.imshow(ob_1copy, 'gray')
plt.axis('off')
plt.savefig("fig2.png")
plt.show()


